app/routes.py
from flask import Flask, flash, Blueprint, render_template, current_app, redirect, url_for, request
from werkzeug.utils import secure_filename
from app.forms import StockForm
from app.models import Stock, User
import os
import uuid
from dataclasses import asdict
from datetime import datetime
import logging
import pymongo

pages = Blueprint(
    "pages", 
    __name__, 
    template_folder="templates", 
    static_folder="static"
)

@pages.route("/", methods=["GET", "POST"])
def index():
    page = request.args.get('page', 1, type= int)
    per_page = 20
    stock_collection = current_app.db.stock

    search_query = request.args.get('search', '')
    receivery_filter = request.args.get('receivery')
    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')

    
    query = {}
    if search_query:
        query['title'] = {'$regex': search_query, '$options': 'i'}

    if receivery_filter:
        query['receivery'] = receivery_filter
    if start_date and end_date:
        query['date'] = {'$gt': datetime.strptime(start_date, '%Y-%m-%d'),
                         '$lte': datetime.strptime(end_date, '%Y-%m-%d')}
        
    stocks = stock_collection.find(query).sort('date', pymongo.DESCENDING).skip((page - 1) * per_page).limit(per_page)
    total_stock = current_app.db.stock.count_documents(query)

    logging.info("Count total stock; %s", total_stock)
    logging.info("Query; %s", query)

    return render_template(
        "index.html",
        title="Stock Tracker", 
        stocks= stocks,
        total_stock= total_stock,
        page= page,
        per_page= per_page,
        search_query = search_query,
        receivery_filter = receivery_filter,
        start_date = start_date,
        end_date = end_date
    )

@pages.route("/test_flash")
def test_flash():
    flash('Flash berhasil ditampilkan', 'message')
    return redirect(url_for(".index"))

@pages.route("/add", methods=["GET", "POST"])
def add_stock():
    page_type = request.args.get('type', 'incoming')
    form = StockForm(page_type=page_type)
    
    if form.validate_on_submit():
        date = datetime.combine(form.date.data, datetime.now().time())

        image_paths = []
        if form.images.data:
            upload_folder = os.path.join(current_app.root_path, 'static', 'media', 'images')
            if not os.path.exists(upload_folder):
                os.makedirs(upload_folder)
            for file in form.images.data:
                filename = secure_filename(file.filename)
                unique_filename = f"{uuid.uuid4().hex}_{filename}"
                file.save(os.path.join(upload_folder, unique_filename))
                image_paths.append(unique_filename)

        stock_data = {
            "_id": uuid.uuid4().hex,
            "title": form.title.data,
            "description": form.description.data,
            "date": date,
            "quantity": form.quantity.data,
            "quantity_type": form.quantity_type.data,
            "serial_number": form.serial_number.data,
            "devision": form.devision.data,
            "sender": form.sender_text.data if page_type == 'incoming' else form.sender_select.data,
            "receivery": form.receivery_text.data if page_type != 'incoming' else form.receivery_select.data,
            "remark": form.remark.data,
            "images": image_paths,
            "is_in_coming": page_type == 'incoming'
        }

        try:
            current_app.db.stock.insert_one(stock_data)
            logging.debug("Stock data inserted successfully")
        except Exception as e:
            logging.error(f"Error inserting stock data into database: {e}")
            form.submit.errors.append("Error inserting data into database")
            return render_template("add_stock.html", title="StockTracker - Tambah Barang", form=form, page_type=page_type)

        return redirect(url_for(".index"))

    if form.errors:
        logging.debug("Form errors: %s", form.errors)

    return render_template("add_stock.html", title="StockTracker - Tambah Barang", form=form, page_type=page_type)


@pages.route("/stock/detail/<string:id>")
def stock_detail(id):
    stock_detail = current_app.db.stock.find_one({"_id": id})
    logging.debug("Data get by ID: %s", stock_detail)
    return render_template("detail.html", stock=stock_detail)


@pages.route("/delete/detail/<string:id>/<string:title>")
def delete_stock(id, title):
    result_deleted = current_app.db.stock.delete_one({'_id': id})
    if result_deleted.deleted_count == 1:
        flash(f'{title} Berhasil dihapus', 'success')
        return redirect(url_for(".index"))
    else:
        flash('Data tidak berhasil dihapus', 'error')

    return redirect(url_for('pages.stock_detail', id = id))

app/templates/add_stock.html
{% from "macros/fields.html" import render_text_field, render_area_field, render_area_images_field %}
{% extends "layout.html" %}


{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}"/>
{% endblock %}

{% block main_content %}
    <form name = "add_stock" method="post" enctype="multipart/form-data" novalidate class="form">
        <div class="form__container">
            
            {% set page_type = request.args.get('type', 'incoming') %}
            
            {% if page_type == 'incoming' %}
                <h1 class="title">{{ texts.new_stock.title_incoming }}</h1>
                <h1 class="sub__title">{{ texts.new_stock.subtitle_incoming }}</h1>
                {{ form.hidden_tag() }}
                {{ render_text_field(form.title) }}
                {{ render_area_field(form.description, 5000)}}
                {{ render_text_field(form.date) }}
                {{ render_text_field(form.quantity) }}
                {{ render_text_field(form.quantity_type) }}
                {{ render_text_field(form.serial_number) }}
                {{ render_text_field(form.devision) }}
                {{ render_text_field(form.sender_text) }}
                {{ render_text_field(form.receivery_select) }}
                {{ render_area_field(form.remark, 1000) }}
                {{ render_area_images_field(form.images) }}
            {% else %}
                <h1 class="title">{{ texts.new_stock.title_outgoing }}</h1>
                <h1 class="sub__title">{{ texts.new_stock.subtitle_outgoing }}</h1>
                {{ form.hidden_tag() }}
                {{ render_text_field(form.title) }}
                {{ render_text_field(form.date) }}
                {{ render_text_field(form.quantity) }}
                {{ render_text_field(form.quantity_type) }}
                {{ render_text_field(form.serial_number) }}
                {{ render_text_field(form.sender_select) }}
                {{ render_text_field(form.receivery_text) }}
                {{ render_text_field(form.devision) }}
                {{ render_area_field(form.remark, 1000) }}
                {{ render_area_images_field(form.images) }}
            {% endif %}
            <div class="form__group">
                {{ form.submit(class="button button--form") }}
            </div>
        </div>
    </form>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const descriptionField = document.querySelector('textarea[name="description"]');
        const remarkField = document.querySelector('textarea[name="remark"]');
        const descriptionCount = document.getElementById('description-count');
        const remarkCount = document.getElementById('remark-count');

        function updateCount(field, countElement, maxCount) {
            field.addEventListener('input', function() {
                const currentCount = field.value.length;
                countElement.textContent = `${currentCount}/${maxCount}`;
            });
        }

        if (descriptionField && descriptionCount) {
            updateCount(descriptionField, descriptionCount, 5000);
        }

        if (remarkField && remarkCount) {
            updateCount(remarkField, remarkCount, 1000);
        }
    });
</script>
{% endblock %}

app/templates/detail.html
{% extends "layout.html" %}

{% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/detail.css') }}">
{% endblock %}

{% block main_content %}
<div class="detail-container">
    <div class="detail-header">
        <h1>{{ stock.title }}</h1>
        <span class="status {% if stock.is_in_coming %}in{% else %}out{% endif %}">
            {% if stock.is_in_coming %}Masuk{% else %}Keluar{% endif %}
        </span>
    </div>

    <div class="detail-body">
        <div class="detail-images">
            {% if stock.images %}
                {% for image in stock.images %}
                    <img src="{{ url_for('static', filename='media/images/' ~ image) }}" alt="Stock Image">
                {% endfor %}
            {% else %}
                <img src="{{ url_for('static', filename='media/images/no_image_default.jpg') }}" alt="Default Image">
            {% endif %}
        </div>

        <div class="detail-info">
            <p><strong>Deskripsi:</strong> {{ stock.description }}</p>
            <p><strong>Tanggal:</strong> {{ stock.date.strftime('%Y-%m-%d') }}</p>
            <p><strong>Jumlah:</strong> {{ stock.quantity }} {{ stock.quantity_type }}</p>
            <p><strong>Pengirim:</strong> {{ stock.sender }}</p>
            <p><strong>Penerima:</strong> {{ stock.receivery }}</p>
            <p><strong>Remark:</strong> {{ stock.remark }}</p>
        </div>
    </div>

    <div class="detail-footer">
        <a href="#" class="button">Edit</a>
        <a href="#" class="button" id="delButton">Hapus</a>
        <a href="#" class="button">Kembali</a>
    </div>
</div>

<div id="popup" class="popup hidden">
    <div class="popup-content">
        <button id="closePopup" class="close-popup">&times;</button>
        <h2>Anda yakin ingin menghapus?</h2>
        <a href="{{ url_for('pages.delete_stock', id= stock._id, title = stock.title) }}" class="button">Hapus</a>
        <button id="closePopupButton" class="button">Tidak</button>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const delButton = document.getElementById('delButton');
        const popup = document.getElementById('popup');
        const closePopup = document.getElementById('closePopup');
        const closePopupButton = document.getElementById('closePopupButton')

        delButton.addEventListener('click', function(event) {
            event.preventDefault();
            popup.classList.remove('hidden');
        });

        closePopup.addEventListener('click', function() {
            popup.classList.add('hidden');
        });

        closePopupButton.addEventListener('click', function() {
            popup.classList.add('hidden');
        });

        window.addEventListener('click', function(event) {
            if (event.target == popup) {
                popup.classList.add('hidden');
            }
        });
    });
</script>
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}

{% block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block main_content %}

<div class="search-filter">

    <img class="img-cover" src="{{ url_for('static', filename='media/main-cover.jpg')}}" alt="main cover">

    <form class="form_search" action="{{ url_for('pages.index') }}" method="get">
        <input type="text" placeholder="Nama barang..." name="search">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>

    <!-- Filters -->
    <form class="form_filter_byname" id="filterFormByName">
        <!-- Filter by Receiver -->
        <select name="receivery" onchange="submitFilterFormByName()">
            <option value="">Penerima</option>
            <option value="Irwan" {% if request.args.get('receivery') == 'Irwan' %}selected{% endif %}>Irwan</option>
            <option value="Suhendri" {% if request.args.get('receivery') == 'Suhendri' %}selected{% endif %}>Suhendri</option>
        </select>
    </form>

    <form class="form_filter_bydate" id="filterFormByDate">
        <!-- Filter by Date Range -->
        <label for="start_date">Tanggal:</label>
        <input type="date" id="start_date" name="start_date" value="{{ request.args.get('start_date', '') }}" onchange="submitFilterFormByDate()">
        <label for="end_date">-</label>
        <input type="date" id="end_date" name="end_date" value="{{ request.args.get('end_date', '') }}" onchange="submitFilterFormByDate()">
    </form>

    <div class="result-filter">
        <div class="result-total"><p>Total:{{total_stock}}</p></div>
        
        <div class="show-result">
            {% if search_query %}
                <p>Mencari: <strong>{{ search_query }}</strong>  
            {% endif %}

            {% if receivery_filter %}
                <p>Penertima: <strong>{{ receivery_filter }}</strong></p>
            {% endif %}

            {% if start_date and end_date %}
                <p>Tanggal: <strong>{{ start_date }}</strong> - <strong>{{ end_date }}</strong></p>
            {% endif %}
        </div>

        {% if search_query or receivery_filter or (start_date and end_date) %}
            <a href="{{ url_for('pages.index') }}" class="button reset-filter">Atur Ulang</a>
        {% endif %}

    </div>

</div>

<div class="list_container">
    {% if total_stock > 0 %}
        {% for stock in stocks %}
        <a href="{{ url_for('pages.stock_detail', id = stock._id) }}" class="list_item-link">
            <div class="list_item {% if stock.is_in_coming %}incoming{% else %}outgoing{% endif %}">
                <div class="list_image">
                    {% if stock.images %}
                        <img src="{{ url_for('static', filename='media/images/' ~ stock.images[0]) }}" alt="Stock Image">
                    {% else %}
                        <img src="{{ url_for('static', filename='media/images/no_image_default.jpg') }}" alt="Default Image">
                    {% endif %}
                </div>
                <div class="list_info">
                    <h3>{{ stock.title }}</h3>
                    <p>{{ stock.date.strftime('%Y-%m-%d') }}</p>
                    <p>Pengirim: {{ stock.sender }}</p>
                    <p>Penerima: {{ stock.receivery }}</p>
                </div>
                <div class="list_status">
                    {% if stock.is_in_coming %}
                        <span class="status in">Masuk</span>
                    {% else %}
                        <span class="status out">Keluar</span>
                    {% endif %}
                </div>
            </div>
        </a>
        {% endfor %}

        <div class="pagination">
            {% if page > 1 %}
                <a href="{{ url_for('pages.index', page = page-1) }}">{{ texts.main.previous }}</a>
            {% endif %}

            {% for p in range(1, (total_stock // per_page) + 2) %}
                {% if p == page %}
                    <strong>{{ p }}</strong>
                {% else %}
                    <a href="{{ url_for('pages.index', page=p) }}">{{ p }}</a>
                {% endif %}
            {% endfor %}

            {% if page < (total_stock // per_page) + 1 %}
                <a href="{{ url_for('pages.index', page=page+1) }}">{{ texts.main.next }}</a>
            {% endif %}
        </div>
    {% else %}
        <h1>Belum ada data</h1>
    {% endif %}
</div>


<a href="{{ url_for('pages.add_stock', type='incoming')}}" class="button button--floating">
    <span>+</span>
</a>

<div id="popup" class="popup hidden">
    <div class="popup-content">
        <button id="closePopup" class="close-popup">&times;</button>
        <h2>Pencatatan</h2>
        <a href="{{ url_for('pages.add_stock', type='incoming')}}" class="button button--action">Barang Masuk</a>
        <a href="{{ url_for('pages.add_stock', type='outgoing')}}" class="button button--action">Barang Keluar</a>
    </div>
</div>

{% endblock %}


{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const addButton = document.getElementById('addButton');
        const popup = document.getElementById('popup');
        const closePopup = document.getElementById('closePopup');

        addButton.addEventListener('click', function(event) {
            event.preventDefault();
            popup.classList.remove('hidden');
        });

        closePopup.addEventListener('click', function() {
            popup.classList.add('hidden');
        });

        window.addEventListener('click', function(event) {
            if (event.target === popup) {
                popup.classList.add('hidden');
            }
        });
    });

    function submitFilterFormByName() {
        document.getElementById('filterFormByName').submit();
    }

    function submitFilterFormByDate() {
        document.getElementById('filterFormByDate').submit();
    }
</script>
{% endblock %}

app/templates/layout.html
{% from "macros/nav.html" import header %}
{% from "macros/footer.html" import footer %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie-edge" />
    <title>{{ title | default ('Stock Tracker') }}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/nav.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/auth/login.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/auth/register.css') }}"/>
    
    {% block head_content %}

    {% endblock %}

</head>


<body>

    {{ header(session.get("email"), session.get("profile_picture")) }}
    
    <main class="main">

    <!-- Flash messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div id="flash-messages">
                {% for category, message in messages %}
                    <div class="flash {{ category }}">
                        {{ message }}
                        <button class="close-btn">&times;</button>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}

        {% block main_content %} 

        {% endblock %}
    </main>

    {% block scripts %} 
    {% endblock %}

    {{ footer() }}

    <script>
        setTimeout(function(){
            const flashMessages = document.getElementById('flash-messages');
            if (flashMessages) {
                flashMessages.style.display = 'none';
            }
        }, 5000);

        document.querySelectorAll('.flash .close-btn').forEach(button => {
            button.addEventListener('click', function() {
                this.parentElement.style.display = 'none';
            });
        });
    </script>
</body>
</html>